// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

syntax = "proto3";

option csharp_namespace = "Dapr.DurableTask.Protobuf";
option java_package = "io.dapr.durabletask.implementation.protobuf";
option go_package = "/api/protos";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

message ScheduleTaskAction {
    string name = 1;
    google.protobuf.StringValue input = 3;
    optional TaskRouter router = 4;
    string taskExecutionId = 5;
}

message CreateSubOrchestrationAction {
    string instanceId = 1;
    string name = 2;
    google.protobuf.StringValue input = 4;
    optional TaskRouter router = 5;
}

message CreateTimerAction {
    google.protobuf.Timestamp fireAt = 1;
    optional string name = 2;
}

message CompleteOrchestrationAction {
    OrchestrationStatus orchestrationStatus = 1;
    google.protobuf.StringValue result = 2;
    google.protobuf.StringValue details = 3;
    repeated HistoryEvent carryoverEvents = 5;
    TaskFailureDetails failureDetails = 6;
}

message TerminateOrchestrationAction {
    string instanceId = 1;
    google.protobuf.StringValue reason = 2;
    bool recurse = 3;
}

message OrchestratorAction {
    int32 id = 1;
    oneof orchestratorActionType {
        ScheduleTaskAction scheduleTask = 2;
        CreateSubOrchestrationAction createSubOrchestration = 3;
        CreateTimerAction createTimer = 4;
        CompleteOrchestrationAction completeOrchestration = 6;
        TerminateOrchestrationAction terminateOrchestration = 7;
    }
    optional TaskRouter router = 9;
}

message OrchestratorResponse {
    string instanceId = 1;
    repeated OrchestratorAction actions = 2;
    google.protobuf.StringValue customStatus = 3;
    string completionToken = 4;

    // The number of work item events that were processed by the orchestrator.
    // This field is optional. If not set, the service should assume that the
    // orchestrator processed all events.
    google.protobuf.Int32Value numEventsProcessed = 5;

    optional OrchestrationVersion version = 6;
}

message OrchestrationState {
    string instanceID = 1;
    string name = 2;
    OrchestrationStatus orchestrationStatus = 4;
    google.protobuf.Timestamp scheduledStartTimestamp = 5;
    google.protobuf.Timestamp createdTimestamp = 6;
    google.protobuf.Timestamp lastUpdatedTimestamp = 7;
    google.protobuf.StringValue input = 8;
    google.protobuf.StringValue output = 9;
    google.protobuf.StringValue customStatus = 10;
    TaskFailureDetails failureDetails = 11;
    google.protobuf.StringValue executionID = 12;
    google.protobuf.Timestamp completedTimestamp = 13;
    google.protobuf.StringValue parentInstanceID = 14;
    map<string, string> tags = 15;
}
