// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

syntax = "proto3";

option csharp_namespace = "Dapr.DurableTask.Protobuf";
option java_package = "io.dapr.durabletask.implementation.protobuf";
option go_package = "/api/protos";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

import "state.proto";
import "tracing.proto";
import "rerun.proto";
import "version.proto";

message ParentInstanceInfo {
    int32 taskScheduledId = 1;
    google.protobuf.StringValue name = 2;
    WorkflowInstance workflowInstance = 4;
    optional string appID = 5;
}

message ExecutionStartedEvent {
    string name = 1;
    google.protobuf.StringValue input = 3;
    WorkflowInstance workflowInstance = 4;
    optional ParentInstanceInfo parentInstance = 5;
    google.protobuf.Timestamp scheduledStartTimestamp = 6;
    TraceContext parentTraceContext = 7;
    google.protobuf.StringValue workflowSpanID = 8;
    map<string, string> tags = 9;
}

message ExecutionCompletedEvent {
    WorkflowStatus workflowStatus = 1;
    google.protobuf.StringValue result = 2;
    TaskFailureDetails failureDetails = 3;
}

message ExecutionTerminatedEvent {
    google.protobuf.StringValue input = 1;
    bool recurse = 2;
}

message TaskScheduledEvent {
    string name = 1;
    google.protobuf.StringValue input = 3;
    TraceContext parentTraceContext = 4;
    string taskExecutionID = 5;

    // If defined, indicates that this task was the starting point of a new
    // workflow execution as the result of a rerun operation.
    optional RerunParentInstanceInfo rerunParentInstanceInfo = 6;
}

message TaskCompletedEvent {
    int32 taskScheduledID = 1;
    google.protobuf.StringValue result = 2;
    string taskExecutionID = 3;
}

message TaskFailedEvent {
    int32 taskScheduledID = 1;
    TaskFailureDetails failureDetails = 2;
    string taskExecutionID = 3;
}

message ChildWorkflowInstanceCreatedEvent {
    string instanceID = 1;
    string name = 2;
    google.protobuf.StringValue input = 4;
    TraceContext parentTraceContext = 5;
}

message ChildWorkflowInstanceCompletedEvent {
    int32 taskScheduledID = 1;
    google.protobuf.StringValue result = 2;
}

message ChildWorkflowInstanceFailedEvent {
    int32 taskScheduledID = 1;
    TaskFailureDetails failureDetails = 2;
}

message TimerCreatedEvent {
    google.protobuf.Timestamp fireAt = 1;
    optional string name = 2;

    // If defined, indicates that this task was the starting point of a new
    // workflow execution as the result of a rerun operation.
    optional RerunParentInstanceInfo rerunParentInstanceInfo = 3;
}

message TimerFiredEvent {
    google.protobuf.Timestamp fireAt = 1;
    int32 timerID = 2;
}

message WorkflowStartedEvent {
    optional WorkflowVersion version = 1;
}

message EventSentEvent {
    string instanceID = 1;
    string name = 2;
    google.protobuf.StringValue input = 3;
}

message EventRaisedEvent {
    string name = 1;
    google.protobuf.StringValue input = 2;
}

message ContinueAsNewEvent {
    google.protobuf.StringValue input = 1;
}

message ExecutionSuspendedEvent {
    google.protobuf.StringValue input = 1;
}

message ExecutionResumedEvent {
    google.protobuf.StringValue input = 1;
}

message ExecutionStalledEvent {
    StalledReason reason = 1;
    optional string description = 2;
}
