// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

syntax = "proto3";

option csharp_namespace = "Dapr.DurableTask.Protobuf";
option java_package = "io.dapr.durabletask.implementation.protobuf";
option go_package = "/api/protos";

import "google/protobuf/timestamp.proto";

import "state.proto";

message PurgeInstancesRequest {
    oneof request {
        string instanceId = 1;
        // TODO: @joshvanl: implement the filter-based purge.
        PurgeInstanceFilter purgeInstanceFilter = 2;
    }
    bool recursive = 3;

    // force will force a purge of a workflow, regardless of its current
    // runtime state, or whether an active worker can process it, the backend
    // will attempt to delete it anyway. This neccessarily means the purging is
    // executed out side of the workflow state machine, and therefore, can lead
    // to corrupt state or broken workflow execution. Usage of this should
    // _only_ be used when the client knows the workflow is not being currently
    // processed. It is highly recommended to avoid using this flag unless
    // absolutely necessary.
    // Defaults to false.
    optional bool force = 4;
}

// TODO: @joshvanl: implement the filter-based purge.
message PurgeInstanceFilter {
    google.protobuf.Timestamp createdTimeFrom = 1;
    google.protobuf.Timestamp createdTimeTo = 2;
    repeated WorkflowStatus runtimeStatus = 3;
}

message PurgeInstancesResponse {
    int32 deletedInstanceCount = 1;
    // Field 2 is taken, use 3 next.
}
