// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

syntax = "proto3";

option csharp_namespace = "Dapr.DurableTask.Protobuf";
option java_package = "io.dapr.durabletask.implementation.protobuf";
option go_package = "/api/protos";

import "google/protobuf/wrappers.proto";

// RerunWorkflowFromEventRequest is used to rerun a workflow instance from a
// specific event ID.
message RerunWorkflowFromEventRequest {
  // sourceInstanceID is the workflow instance ID to rerun. Can be a top
  // level instance, or sub-workflow instance.
  string sourceInstanceID = 1;

  // the event id to start the new workflow instance from.
  uint32 eventID = 2;

  // newInstanceID is the new instance ID to use for the new workflow instance.
  // If not given, a random instance ID will be given.
  optional string newInstanceID = 3;

  // input can optionally given to give the new instance a different input to
  // the next Activity event.
  google.protobuf.StringValue input = 4;

  // overwrite_input signals that the input to the rerun activity should be
  // written with input. This is required because of the incorrect typing of
  // inputs being `StringValue` which cannot be optional, and therefore no nil
  // value can be signalled or overwritten.
  bool overwriteInput = 5;
}

// RerunWorkflowFromEventResponse is the response to executing
// RerunWorkflowFromEvent.
message RerunWorkflowFromEventResponse {
    string newInstanceID = 1;
}

// RerunParentInstanceInfo is used to indicate that this workflow was
// started as part of a rerun operation. Contains information about the parent
// workflow instance which was rerun.
message RerunParentInstanceInfo {
  // instanceID is the workflow instance ID this workflow has been
  // rerun from.
  string instanceID = 1;
}
