// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

syntax = "proto3";

option csharp_namespace = "Dapr.DurableTask.Protobuf";
option java_package = "io.dapr.durabletask.implementation.protobuf";
option go_package = "/api/protos";

import "google/protobuf/wrappers.proto";

message WorkflowInstance {
    string instanceId = 1;
    google.protobuf.StringValue executionId = 2;
}

message TaskFailureDetails {
    string errorType = 1;
    string errorMessage = 2;
    google.protobuf.StringValue stackTrace = 3;
    TaskFailureDetails innerFailure = 4;
    bool isNonRetriable = 5;
}

enum WorkflowStatus {
    WORKFLOW_STATUS_RUNNING = 0;
    WORKFLOW_STATUS_COMPLETED = 1;
    WORKFLOW_STATUS_CONTINUED_AS_NEW = 2;
    WORKFLOW_STATUS_FAILED = 3;
    WORKFLOW_STATUS_CANCELED = 4;
    WORKFLOW_STATUS_TERMINATED = 5;
    WORKFLOW_STATUS_PENDING = 6;
    WORKFLOW_STATUS_SUSPENDED = 7;
    WORKFLOW_STATUS_STALLED = 8;
}
