// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.32.1
// source: purge.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurgeInstancesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*PurgeInstancesRequest_InstanceId
	//	*PurgeInstancesRequest_PurgeInstanceFilter
	Request   isPurgeInstancesRequest_Request `protobuf_oneof:"request"`
	Recursive bool                            `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	// force will force a purge of a workflow, regardless of its current
	// runtime state, or whether an active worker can process it, the backend
	// will attempt to delete it anyway. This neccessarily means the purging is
	// executed out side of the workflow state machine, and therefore, can lead
	// to corrupt state or broken workflow execution. Usage of this should
	// _only_ be used when the client knows the workflow is not being currently
	// processed. It is highly recommended to avoid using this flag unless
	// absolutely necessary.
	// Defaults to false.
	Force *bool `protobuf:"varint,4,opt,name=force,proto3,oneof" json:"force,omitempty"`
}

func (x *PurgeInstancesRequest) Reset() {
	*x = PurgeInstancesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeInstancesRequest) ProtoMessage() {}

func (x *PurgeInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeInstancesRequest.ProtoReflect.Descriptor instead.
func (*PurgeInstancesRequest) Descriptor() ([]byte, []int) {
	return file_purge_proto_rawDescGZIP(), []int{0}
}

func (m *PurgeInstancesRequest) GetRequest() isPurgeInstancesRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *PurgeInstancesRequest) GetInstanceId() string {
	if x, ok := x.GetRequest().(*PurgeInstancesRequest_InstanceId); ok {
		return x.InstanceId
	}
	return ""
}

func (x *PurgeInstancesRequest) GetPurgeInstanceFilter() *PurgeInstanceFilter {
	if x, ok := x.GetRequest().(*PurgeInstancesRequest_PurgeInstanceFilter); ok {
		return x.PurgeInstanceFilter
	}
	return nil
}

func (x *PurgeInstancesRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *PurgeInstancesRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

type isPurgeInstancesRequest_Request interface {
	isPurgeInstancesRequest_Request()
}

type PurgeInstancesRequest_InstanceId struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instanceId,proto3,oneof"`
}

type PurgeInstancesRequest_PurgeInstanceFilter struct {
	// TODO: @joshvanl: implement the filter-based purge.
	PurgeInstanceFilter *PurgeInstanceFilter `protobuf:"bytes,2,opt,name=purgeInstanceFilter,proto3,oneof"`
}

func (*PurgeInstancesRequest_InstanceId) isPurgeInstancesRequest_Request() {}

func (*PurgeInstancesRequest_PurgeInstanceFilter) isPurgeInstancesRequest_Request() {}

// TODO: @joshvanl: implement the filter-based purge.
type PurgeInstanceFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedTimeFrom *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=createdTimeFrom,proto3" json:"createdTimeFrom,omitempty"`
	CreatedTimeTo   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdTimeTo,proto3" json:"createdTimeTo,omitempty"`
	RuntimeStatus   []WorkflowStatus       `protobuf:"varint,3,rep,packed,name=runtimeStatus,proto3,enum=WorkflowStatus" json:"runtimeStatus,omitempty"`
}

func (x *PurgeInstanceFilter) Reset() {
	*x = PurgeInstanceFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeInstanceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeInstanceFilter) ProtoMessage() {}

func (x *PurgeInstanceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_purge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeInstanceFilter.ProtoReflect.Descriptor instead.
func (*PurgeInstanceFilter) Descriptor() ([]byte, []int) {
	return file_purge_proto_rawDescGZIP(), []int{1}
}

func (x *PurgeInstanceFilter) GetCreatedTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimeFrom
	}
	return nil
}

func (x *PurgeInstanceFilter) GetCreatedTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimeTo
	}
	return nil
}

func (x *PurgeInstanceFilter) GetRuntimeStatus() []WorkflowStatus {
	if x != nil {
		return x.RuntimeStatus
	}
	return nil
}

type PurgeInstancesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedInstanceCount int32 `protobuf:"varint,1,opt,name=deletedInstanceCount,proto3" json:"deletedInstanceCount,omitempty"` // Field 2 is taken, use 3 next.
}

func (x *PurgeInstancesResponse) Reset() {
	*x = PurgeInstancesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurgeInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeInstancesResponse) ProtoMessage() {}

func (x *PurgeInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeInstancesResponse.ProtoReflect.Descriptor instead.
func (*PurgeInstancesResponse) Descriptor() ([]byte, []int) {
	return file_purge_proto_rawDescGZIP(), []int{2}
}

func (x *PurgeInstancesResponse) GetDeletedInstanceCount() int32 {
	if x != nil {
		return x.DeletedInstanceCount
	}
	return 0
}

var File_purge_proto protoreflect.FileDescriptor

var file_purge_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x75, 0x72, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x15,
	0x50, 0x75, 0x72, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x48, 0x0a, 0x13, 0x70, 0x75, 0x72, 0x67, 0x65,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x13, 0x70, 0x75,
	0x72, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x12,
	0x19, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01,
	0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22,
	0xd4, 0x01, 0x0a, 0x13, 0x50, 0x75, 0x72, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x40, 0x0a,
	0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x12,
	0x35, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4c, 0x0a, 0x16, 0x50, 0x75, 0x72, 0x67, 0x65, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x14, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x56, 0x0a, 0x2b, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x5a, 0x0b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0xaa, 0x02, 0x19, 0x44, 0x61, 0x70, 0x72, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_purge_proto_rawDescOnce sync.Once
	file_purge_proto_rawDescData = file_purge_proto_rawDesc
)

func file_purge_proto_rawDescGZIP() []byte {
	file_purge_proto_rawDescOnce.Do(func() {
		file_purge_proto_rawDescData = protoimpl.X.CompressGZIP(file_purge_proto_rawDescData)
	})
	return file_purge_proto_rawDescData
}

var file_purge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_purge_proto_goTypes = []interface{}{
	(*PurgeInstancesRequest)(nil),  // 0: PurgeInstancesRequest
	(*PurgeInstanceFilter)(nil),    // 1: PurgeInstanceFilter
	(*PurgeInstancesResponse)(nil), // 2: PurgeInstancesResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(WorkflowStatus)(0),            // 4: WorkflowStatus
}
var file_purge_proto_depIdxs = []int32{
	1, // 0: PurgeInstancesRequest.purgeInstanceFilter:type_name -> PurgeInstanceFilter
	3, // 1: PurgeInstanceFilter.createdTimeFrom:type_name -> google.protobuf.Timestamp
	3, // 2: PurgeInstanceFilter.createdTimeTo:type_name -> google.protobuf.Timestamp
	4, // 3: PurgeInstanceFilter.runtimeStatus:type_name -> WorkflowStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_purge_proto_init() }
func file_purge_proto_init() {
	if File_purge_proto != nil {
		return
	}
	file_state_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_purge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeInstancesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_purge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeInstanceFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_purge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurgeInstancesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_purge_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PurgeInstancesRequest_InstanceId)(nil),
		(*PurgeInstancesRequest_PurgeInstanceFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_purge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_purge_proto_goTypes,
		DependencyIndexes: file_purge_proto_depIdxs,
		MessageInfos:      file_purge_proto_msgTypes,
	}.Build()
	File_purge_proto = out.File
	file_purge_proto_rawDesc = nil
	file_purge_proto_goTypes = nil
	file_purge_proto_depIdxs = nil
}
