// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.32.1
// source: rerun.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RerunWorkflowFromEventRequest is used to rerun a workflow instance from a
// specific event ID.
type RerunWorkflowFromEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sourceInstanceID is the workflow instance ID to rerun. Can be a top
	// level instance, or sub-workflow instance.
	SourceInstanceID string `protobuf:"bytes,1,opt,name=sourceInstanceID,proto3" json:"sourceInstanceID,omitempty"`
	// the event id to start the new workflow instance from.
	EventID uint32 `protobuf:"varint,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	// newInstanceID is the new instance ID to use for the new workflow instance.
	// If not given, a random instance ID will be given.
	NewInstanceID *string `protobuf:"bytes,3,opt,name=newInstanceID,proto3,oneof" json:"newInstanceID,omitempty"`
	// input can optionally given to give the new instance a different input to
	// the next Activity event.
	Input *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	// overwrite_input signals that the input to the rerun activity should be
	// written with input. This is required because of the incorrect typing of
	// inputs being `StringValue` which cannot be optional, and therefore no nil
	// value can be signalled or overwritten.
	OverwriteInput bool `protobuf:"varint,5,opt,name=overwriteInput,proto3" json:"overwriteInput,omitempty"`
}

func (x *RerunWorkflowFromEventRequest) Reset() {
	*x = RerunWorkflowFromEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rerun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RerunWorkflowFromEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerunWorkflowFromEventRequest) ProtoMessage() {}

func (x *RerunWorkflowFromEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rerun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerunWorkflowFromEventRequest.ProtoReflect.Descriptor instead.
func (*RerunWorkflowFromEventRequest) Descriptor() ([]byte, []int) {
	return file_rerun_proto_rawDescGZIP(), []int{0}
}

func (x *RerunWorkflowFromEventRequest) GetSourceInstanceID() string {
	if x != nil {
		return x.SourceInstanceID
	}
	return ""
}

func (x *RerunWorkflowFromEventRequest) GetEventID() uint32 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *RerunWorkflowFromEventRequest) GetNewInstanceID() string {
	if x != nil && x.NewInstanceID != nil {
		return *x.NewInstanceID
	}
	return ""
}

func (x *RerunWorkflowFromEventRequest) GetInput() *wrapperspb.StringValue {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RerunWorkflowFromEventRequest) GetOverwriteInput() bool {
	if x != nil {
		return x.OverwriteInput
	}
	return false
}

// RerunWorkflowFromEventResponse is the response to executing
// RerunWorkflowFromEvent.
type RerunWorkflowFromEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewInstanceID string `protobuf:"bytes,1,opt,name=newInstanceID,proto3" json:"newInstanceID,omitempty"`
}

func (x *RerunWorkflowFromEventResponse) Reset() {
	*x = RerunWorkflowFromEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rerun_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RerunWorkflowFromEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerunWorkflowFromEventResponse) ProtoMessage() {}

func (x *RerunWorkflowFromEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rerun_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerunWorkflowFromEventResponse.ProtoReflect.Descriptor instead.
func (*RerunWorkflowFromEventResponse) Descriptor() ([]byte, []int) {
	return file_rerun_proto_rawDescGZIP(), []int{1}
}

func (x *RerunWorkflowFromEventResponse) GetNewInstanceID() string {
	if x != nil {
		return x.NewInstanceID
	}
	return ""
}

// RerunParentInstanceInfo is used to indicate that this workflow was
// started as part of a rerun operation. Contains information about the parent
// workflow instance which was rerun.
type RerunParentInstanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// instanceID is the workflow instance ID this workflow has been
	// rerun from.
	InstanceID string `protobuf:"bytes,1,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
}

func (x *RerunParentInstanceInfo) Reset() {
	*x = RerunParentInstanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rerun_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RerunParentInstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerunParentInstanceInfo) ProtoMessage() {}

func (x *RerunParentInstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rerun_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerunParentInstanceInfo.ProtoReflect.Descriptor instead.
func (*RerunParentInstanceInfo) Descriptor() ([]byte, []int) {
	return file_rerun_proto_rawDescGZIP(), []int{2}
}

func (x *RerunParentInstanceInfo) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

var File_rerun_proto protoreflect.FileDescriptor

var file_rerun_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x72, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe, 0x01,
	0x0a, 0x1d, 0x52, 0x65, 0x72, 0x75, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x46,
	0x72, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d,
	0x6e, 0x65, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x88, 0x01, 0x01,
	0x12, 0x32, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6f, 0x76,
	0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x10, 0x0a, 0x0e,
	0x5f, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x46,
	0x0a, 0x1e, 0x52, 0x65, 0x72, 0x75, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x46,
	0x72, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x17, 0x52, 0x65, 0x72, 0x75, 0x6e, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x42, 0x56, 0x0a, 0x2b, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x64, 0x75, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x5a, 0x0b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa, 0x02, 0x19,
	0x44, 0x61, 0x70, 0x72, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rerun_proto_rawDescOnce sync.Once
	file_rerun_proto_rawDescData = file_rerun_proto_rawDesc
)

func file_rerun_proto_rawDescGZIP() []byte {
	file_rerun_proto_rawDescOnce.Do(func() {
		file_rerun_proto_rawDescData = protoimpl.X.CompressGZIP(file_rerun_proto_rawDescData)
	})
	return file_rerun_proto_rawDescData
}

var file_rerun_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rerun_proto_goTypes = []interface{}{
	(*RerunWorkflowFromEventRequest)(nil),  // 0: RerunWorkflowFromEventRequest
	(*RerunWorkflowFromEventResponse)(nil), // 1: RerunWorkflowFromEventResponse
	(*RerunParentInstanceInfo)(nil),        // 2: RerunParentInstanceInfo
	(*wrapperspb.StringValue)(nil),         // 3: google.protobuf.StringValue
}
var file_rerun_proto_depIdxs = []int32{
	3, // 0: RerunWorkflowFromEventRequest.input:type_name -> google.protobuf.StringValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rerun_proto_init() }
func file_rerun_proto_init() {
	if File_rerun_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rerun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RerunWorkflowFromEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rerun_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RerunWorkflowFromEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rerun_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RerunParentInstanceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rerun_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rerun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rerun_proto_goTypes,
		DependencyIndexes: file_rerun_proto_depIdxs,
		MessageInfos:      file_rerun_proto_msgTypes,
	}.Build()
	File_rerun_proto = out.File
	file_rerun_proto_rawDesc = nil
	file_rerun_proto_goTypes = nil
	file_rerun_proto_depIdxs = nil
}
