// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: workflow.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Workflows_ScheduleInstance_FullMethodName          = "/Workflows/ScheduleInstance"
	Workflows_GetInstance_FullMethodName               = "/Workflows/GetInstance"
	Workflows_WaitForInstanceStart_FullMethodName      = "/Workflows/WaitForInstanceStart"
	Workflows_WaitForInstanceCompletion_FullMethodName = "/Workflows/WaitForInstanceCompletion"
	Workflows_RaiseEvent_FullMethodName                = "/Workflows/RaiseEvent"
	Workflows_TerminateInstance_FullMethodName         = "/Workflows/TerminateInstance"
	Workflows_SuspendInstance_FullMethodName           = "/Workflows/SuspendInstance"
	Workflows_ResumeInstance_FullMethodName            = "/Workflows/ResumeInstance"
	Workflows_RerunWorkflowFromEvent_FullMethodName    = "/Workflows/RerunWorkflowFromEvent"
	Workflows_ListInstanceIDs_FullMethodName           = "/Workflows/ListInstanceIDs"
	Workflows_GetInstanceHistory_FullMethodName        = "/Workflows/GetInstanceHistory"
)

// WorkflowsClient is the client API for Workflows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowsClient interface {
	// Starts a new workflow instance.
	ScheduleInstance(ctx context.Context, in *ScheduleInstanceRequest, opts ...grpc.CallOption) (*ScheduleInstanceResponse, error)
	// Gets the status of an existing workflow instance.
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Waits for an workflow instance to reach a running or completion state.
	WaitForInstanceStart(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Waits for an workflow instance to reach a completion state (completed, failed, terminated, etc.).
	WaitForInstanceCompletion(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Raises an event to a running workflow instance.
	RaiseEvent(ctx context.Context, in *RaiseEventRequest, opts ...grpc.CallOption) (*RaiseEventResponse, error)
	// Terminates a running workflow instance.
	TerminateInstance(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	// Suspends a running workflow instance.
	SuspendInstance(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error)
	// Resumes a suspended workflow instance.
	ResumeInstance(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	// Rerun a Workflow from a specific event ID of a workflow instance.
	RerunWorkflowFromEvent(ctx context.Context, in *RerunWorkflowFromEventRequest, opts ...grpc.CallOption) (*RerunWorkflowFromEventResponse, error)
	// List all workflow instance IDs.
	ListInstanceIDs(ctx context.Context, in *ListInstanceIDsRequest, opts ...grpc.CallOption) (*ListInstanceIDsResponse, error)
	// Gets the full history of a workflow instance.
	GetInstanceHistory(ctx context.Context, in *GetInstanceHistoryRequest, opts ...grpc.CallOption) (*GetInstanceHistoryResponse, error)
}

type workflowsClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowsClient(cc grpc.ClientConnInterface) WorkflowsClient {
	return &workflowsClient{cc}
}

func (c *workflowsClient) ScheduleInstance(ctx context.Context, in *ScheduleInstanceRequest, opts ...grpc.CallOption) (*ScheduleInstanceResponse, error) {
	out := new(ScheduleInstanceResponse)
	err := c.cc.Invoke(ctx, Workflows_ScheduleInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, Workflows_GetInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) WaitForInstanceStart(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, Workflows_WaitForInstanceStart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) WaitForInstanceCompletion(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, Workflows_WaitForInstanceCompletion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) RaiseEvent(ctx context.Context, in *RaiseEventRequest, opts ...grpc.CallOption) (*RaiseEventResponse, error) {
	out := new(RaiseEventResponse)
	err := c.cc.Invoke(ctx, Workflows_RaiseEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) TerminateInstance(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, Workflows_TerminateInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) SuspendInstance(ctx context.Context, in *SuspendRequest, opts ...grpc.CallOption) (*SuspendResponse, error) {
	out := new(SuspendResponse)
	err := c.cc.Invoke(ctx, Workflows_SuspendInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) ResumeInstance(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, Workflows_ResumeInstance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) RerunWorkflowFromEvent(ctx context.Context, in *RerunWorkflowFromEventRequest, opts ...grpc.CallOption) (*RerunWorkflowFromEventResponse, error) {
	out := new(RerunWorkflowFromEventResponse)
	err := c.cc.Invoke(ctx, Workflows_RerunWorkflowFromEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) ListInstanceIDs(ctx context.Context, in *ListInstanceIDsRequest, opts ...grpc.CallOption) (*ListInstanceIDsResponse, error) {
	out := new(ListInstanceIDsResponse)
	err := c.cc.Invoke(ctx, Workflows_ListInstanceIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsClient) GetInstanceHistory(ctx context.Context, in *GetInstanceHistoryRequest, opts ...grpc.CallOption) (*GetInstanceHistoryResponse, error) {
	out := new(GetInstanceHistoryResponse)
	err := c.cc.Invoke(ctx, Workflows_GetInstanceHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowsServer is the server API for Workflows service.
// All implementations must embed UnimplementedWorkflowsServer
// for forward compatibility
type WorkflowsServer interface {
	// Starts a new workflow instance.
	ScheduleInstance(context.Context, *ScheduleInstanceRequest) (*ScheduleInstanceResponse, error)
	// Gets the status of an existing workflow instance.
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Waits for an workflow instance to reach a running or completion state.
	WaitForInstanceStart(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Waits for an workflow instance to reach a completion state (completed, failed, terminated, etc.).
	WaitForInstanceCompletion(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Raises an event to a running workflow instance.
	RaiseEvent(context.Context, *RaiseEventRequest) (*RaiseEventResponse, error)
	// Terminates a running workflow instance.
	TerminateInstance(context.Context, *TerminateRequest) (*TerminateResponse, error)
	// Suspends a running workflow instance.
	SuspendInstance(context.Context, *SuspendRequest) (*SuspendResponse, error)
	// Resumes a suspended workflow instance.
	ResumeInstance(context.Context, *ResumeRequest) (*ResumeResponse, error)
	// Rerun a Workflow from a specific event ID of a workflow instance.
	RerunWorkflowFromEvent(context.Context, *RerunWorkflowFromEventRequest) (*RerunWorkflowFromEventResponse, error)
	// List all workflow instance IDs.
	ListInstanceIDs(context.Context, *ListInstanceIDsRequest) (*ListInstanceIDsResponse, error)
	// Gets the full history of a workflow instance.
	GetInstanceHistory(context.Context, *GetInstanceHistoryRequest) (*GetInstanceHistoryResponse, error)
	mustEmbedUnimplementedWorkflowsServer()
}

// UnimplementedWorkflowsServer must be embedded to have forward compatible implementations.
type UnimplementedWorkflowsServer struct {
}

func (UnimplementedWorkflowsServer) ScheduleInstance(context.Context, *ScheduleInstanceRequest) (*ScheduleInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleInstance not implemented")
}
func (UnimplementedWorkflowsServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedWorkflowsServer) WaitForInstanceStart(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForInstanceStart not implemented")
}
func (UnimplementedWorkflowsServer) WaitForInstanceCompletion(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForInstanceCompletion not implemented")
}
func (UnimplementedWorkflowsServer) RaiseEvent(context.Context, *RaiseEventRequest) (*RaiseEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RaiseEvent not implemented")
}
func (UnimplementedWorkflowsServer) TerminateInstance(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateInstance not implemented")
}
func (UnimplementedWorkflowsServer) SuspendInstance(context.Context, *SuspendRequest) (*SuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendInstance not implemented")
}
func (UnimplementedWorkflowsServer) ResumeInstance(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeInstance not implemented")
}
func (UnimplementedWorkflowsServer) RerunWorkflowFromEvent(context.Context, *RerunWorkflowFromEventRequest) (*RerunWorkflowFromEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RerunWorkflowFromEvent not implemented")
}
func (UnimplementedWorkflowsServer) ListInstanceIDs(context.Context, *ListInstanceIDsRequest) (*ListInstanceIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstanceIDs not implemented")
}
func (UnimplementedWorkflowsServer) GetInstanceHistory(context.Context, *GetInstanceHistoryRequest) (*GetInstanceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceHistory not implemented")
}
func (UnimplementedWorkflowsServer) mustEmbedUnimplementedWorkflowsServer() {}

// UnsafeWorkflowsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowsServer will
// result in compilation errors.
type UnsafeWorkflowsServer interface {
	mustEmbedUnimplementedWorkflowsServer()
}

func RegisterWorkflowsServer(s grpc.ServiceRegistrar, srv WorkflowsServer) {
	s.RegisterService(&Workflows_ServiceDesc, srv)
}

func _Workflows_ScheduleInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).ScheduleInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_ScheduleInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).ScheduleInstance(ctx, req.(*ScheduleInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_WaitForInstanceStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).WaitForInstanceStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_WaitForInstanceStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).WaitForInstanceStart(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_WaitForInstanceCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).WaitForInstanceCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_WaitForInstanceCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).WaitForInstanceCompletion(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_RaiseEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaiseEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).RaiseEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_RaiseEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).RaiseEvent(ctx, req.(*RaiseEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_TerminateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).TerminateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_TerminateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).TerminateInstance(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_SuspendInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).SuspendInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_SuspendInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).SuspendInstance(ctx, req.(*SuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_ResumeInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).ResumeInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_ResumeInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).ResumeInstance(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_RerunWorkflowFromEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerunWorkflowFromEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).RerunWorkflowFromEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_RerunWorkflowFromEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).RerunWorkflowFromEvent(ctx, req.(*RerunWorkflowFromEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_ListInstanceIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstanceIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).ListInstanceIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_ListInstanceIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).ListInstanceIDs(ctx, req.(*ListInstanceIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflows_GetInstanceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServer).GetInstanceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Workflows_GetInstanceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServer).GetInstanceHistory(ctx, req.(*GetInstanceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Workflows_ServiceDesc is the grpc.ServiceDesc for Workflows service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workflows_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Workflows",
	HandlerType: (*WorkflowsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleInstance",
			Handler:    _Workflows_ScheduleInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _Workflows_GetInstance_Handler,
		},
		{
			MethodName: "WaitForInstanceStart",
			Handler:    _Workflows_WaitForInstanceStart_Handler,
		},
		{
			MethodName: "WaitForInstanceCompletion",
			Handler:    _Workflows_WaitForInstanceCompletion_Handler,
		},
		{
			MethodName: "RaiseEvent",
			Handler:    _Workflows_RaiseEvent_Handler,
		},
		{
			MethodName: "TerminateInstance",
			Handler:    _Workflows_TerminateInstance_Handler,
		},
		{
			MethodName: "SuspendInstance",
			Handler:    _Workflows_SuspendInstance_Handler,
		},
		{
			MethodName: "ResumeInstance",
			Handler:    _Workflows_ResumeInstance_Handler,
		},
		{
			MethodName: "RerunWorkflowFromEvent",
			Handler:    _Workflows_RerunWorkflowFromEvent_Handler,
		},
		{
			MethodName: "ListInstanceIDs",
			Handler:    _Workflows_ListInstanceIDs_Handler,
		},
		{
			MethodName: "GetInstanceHistory",
			Handler:    _Workflows_GetInstanceHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
