// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: worker.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Worker_GetWorkItems_FullMethodName                = "/Worker/GetWorkItems"
	Worker_CompleteActivityTask_FullMethodName        = "/Worker/CompleteActivityTask"
	Worker_CompleteWorkflowTask_FullMethodName        = "/Worker/CompleteWorkflowTask"
	Worker_AbandonTaskActivityWorkItem_FullMethodName = "/Worker/AbandonTaskActivityWorkItem"
	Worker_AbandonTaskWorkflowWorkItem_FullMethodName = "/Worker/AbandonTaskWorkflowWorkItem"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	GetWorkItems(ctx context.Context, in *GetWorkItemsRequest, opts ...grpc.CallOption) (Worker_GetWorkItemsClient, error)
	CompleteActivityTask(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	CompleteWorkflowTask(ctx context.Context, in *WorkflowResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	AbandonTaskActivityWorkItem(ctx context.Context, in *AbandonActivityTaskRequest, opts ...grpc.CallOption) (*AbandonActivityTaskResponse, error)
	AbandonTaskWorkflowWorkItem(ctx context.Context, in *AbandonWorkflowTaskRequest, opts ...grpc.CallOption) (*AbandonWorkflowTaskResponse, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) GetWorkItems(ctx context.Context, in *GetWorkItemsRequest, opts ...grpc.CallOption) (Worker_GetWorkItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_GetWorkItems_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerGetWorkItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_GetWorkItemsClient interface {
	Recv() (*WorkItem, error)
	grpc.ClientStream
}

type workerGetWorkItemsClient struct {
	grpc.ClientStream
}

func (x *workerGetWorkItemsClient) Recv() (*WorkItem, error) {
	m := new(WorkItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) CompleteActivityTask(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, Worker_CompleteActivityTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) CompleteWorkflowTask(ctx context.Context, in *WorkflowResponse, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, Worker_CompleteWorkflowTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) AbandonTaskActivityWorkItem(ctx context.Context, in *AbandonActivityTaskRequest, opts ...grpc.CallOption) (*AbandonActivityTaskResponse, error) {
	out := new(AbandonActivityTaskResponse)
	err := c.cc.Invoke(ctx, Worker_AbandonTaskActivityWorkItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) AbandonTaskWorkflowWorkItem(ctx context.Context, in *AbandonWorkflowTaskRequest, opts ...grpc.CallOption) (*AbandonWorkflowTaskResponse, error) {
	out := new(AbandonWorkflowTaskResponse)
	err := c.cc.Invoke(ctx, Worker_AbandonTaskWorkflowWorkItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility
type WorkerServer interface {
	GetWorkItems(*GetWorkItemsRequest, Worker_GetWorkItemsServer) error
	CompleteActivityTask(context.Context, *ActivityResponse) (*CompleteTaskResponse, error)
	CompleteWorkflowTask(context.Context, *WorkflowResponse) (*CompleteTaskResponse, error)
	AbandonTaskActivityWorkItem(context.Context, *AbandonActivityTaskRequest) (*AbandonActivityTaskResponse, error)
	AbandonTaskWorkflowWorkItem(context.Context, *AbandonWorkflowTaskRequest) (*AbandonWorkflowTaskResponse, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (UnimplementedWorkerServer) GetWorkItems(*GetWorkItemsRequest, Worker_GetWorkItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWorkItems not implemented")
}
func (UnimplementedWorkerServer) CompleteActivityTask(context.Context, *ActivityResponse) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteActivityTask not implemented")
}
func (UnimplementedWorkerServer) CompleteWorkflowTask(context.Context, *WorkflowResponse) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteWorkflowTask not implemented")
}
func (UnimplementedWorkerServer) AbandonTaskActivityWorkItem(context.Context, *AbandonActivityTaskRequest) (*AbandonActivityTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonTaskActivityWorkItem not implemented")
}
func (UnimplementedWorkerServer) AbandonTaskWorkflowWorkItem(context.Context, *AbandonWorkflowTaskRequest) (*AbandonWorkflowTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonTaskWorkflowWorkItem not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_GetWorkItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWorkItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).GetWorkItems(m, &workerGetWorkItemsServer{stream})
}

type Worker_GetWorkItemsServer interface {
	Send(*WorkItem) error
	grpc.ServerStream
}

type workerGetWorkItemsServer struct {
	grpc.ServerStream
}

func (x *workerGetWorkItemsServer) Send(m *WorkItem) error {
	return x.ServerStream.SendMsg(m)
}

func _Worker_CompleteActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).CompleteActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_CompleteActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).CompleteActivityTask(ctx, req.(*ActivityResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_CompleteWorkflowTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).CompleteWorkflowTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_CompleteWorkflowTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).CompleteWorkflowTask(ctx, req.(*WorkflowResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_AbandonTaskActivityWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonActivityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).AbandonTaskActivityWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_AbandonTaskActivityWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).AbandonTaskActivityWorkItem(ctx, req.(*AbandonActivityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_AbandonTaskWorkflowWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonWorkflowTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).AbandonTaskWorkflowWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_AbandonTaskWorkflowWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).AbandonTaskWorkflowWorkItem(ctx, req.(*AbandonWorkflowTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompleteActivityTask",
			Handler:    _Worker_CompleteActivityTask_Handler,
		},
		{
			MethodName: "CompleteWorkflowTask",
			Handler:    _Worker_CompleteWorkflowTask_Handler,
		},
		{
			MethodName: "AbandonTaskActivityWorkItem",
			Handler:    _Worker_AbandonTaskActivityWorkItem_Handler,
		},
		{
			MethodName: "AbandonTaskWorkflowWorkItem",
			Handler:    _Worker_AbandonTaskWorkflowWorkItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWorkItems",
			Handler:       _Worker_GetWorkItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}
